USE BIBLIOTECA

-- QUANTIDADE DE LIVROS DISPONIVEIS
SELECT COUNT(*) FROM LIVROS

-- AUTORES QUE MAIS PUBLICARAM LIVROS
SELECT A.NOME_AUTOR, 
(SELECT COUNT(LA.ID_AUTOR) FROM LIVROS_AUTOR LA WHERE A.ID_AUTOR = LA.ID_AUTOR) AS LIVROS_ESCRITOS
FROM AUTOR A

-- 