-- QUANTIDADE DE LIVROS DISPONIVEIS
SELECT COUNT(*) FROM LIVROS;

-- AUTORES QUE MAIS PUBLICARAM LIVROS
SELECT A.NOME_AUTOR, 
(SELECT COUNT(LA.ID_AUTOR) FROM LIVROS_AUTOR LA WHERE A.ID_AUTOR = LA.ID_AUTOR) AS LIVROS_ESCRITOS
FROM AUTOR A

-- Valor máximo de multa
SELECT MAX(VALOR_MULTAS) FROM MULTAS;

-- valor minimo da multa
SELECT MIN(VALOR_MULTAS) FROM MULTAS;

-- MÉDIA DO VALOR DAS MULTAS
SELECT AVG(VALOR_MULTAS) FROM MULTAS;

-- TOTAL ARRECADADO COM MULTAS
SELECT SUM(VALOR_MULTAS) FROM MULTAS

-- GANHO PORCENTUAL
SELECT (SUM(VALOR_MULTAS) / COUNT(VALOR_MULTAS)) + '%' AS PORCENTUAL FROM MULTAS 

--  QUANTIDADE DE DEVOLUÇÕES ATRASADA
SELECT COUNT(DATA_DEVOLUCAO) FROM DEVOLUCOES WHERE DATA_DEVOLUCAO != DATA_DEVOLUCAO_ESPERADA

--  QUANTIDADE DE DEVOLUÇÕES CORRETAS
SELECT COUNT(DATA_DEVOLUCAO) FROM DEVOLUCOES WHERE DATA_DEVOLUCAO = DATA_DEVOLUCAO_ESPERADA

-- QUANTIDADE TOTAL DE USUARIOS QUE ALOCARAM ALGUM LIVRO
SELECT SUM(ID_USUARIO) FROM LOCACAO

-- 

