-- CREATE DATABASE TEATRO;
USE TEATRO;

-- 1
CREATE TABLE PECAS_TEATRO(
	ID_PECA INT  PRIMARY KEY AUTO_INCREMENT,
    NOME_PECA VARCHAR(100),
    DESCRICAO VARCHAR(800),
    DURACAO INT,
    TEMA VARCHAR(30),
    HORARIO  TIME
);

INSERT INTO PECAS_TEATRO (NOME_PECA, DESCRICAO, DURACAO, TEMA, HORARIO)
VALUES ('O Fantasma da Ópera', 'Um musical clássico sobre um misterioso fantasma que assombra uma casa de ópera.', 230, 'Drama', '20:00');

INSERT INTO PECAS_TEATRO (NOME_PECA, DESCRICAO, DURACAO, TEMA, HORARIO)
VALUES ('Romeu e Julieta', 'Uma tragédia romântica de Shakespeare sobre dois jovens apaixonados.', 215, 'Tragédia', '19:30');

INSERT INTO PECAS_TEATRO (NOME_PECA, DESCRICAO, DURACAO, TEMA, HORARIO)
VALUES ('A Bela e a Fera', 'Uma adaptação teatral do conto de fadas sobre o amor verdadeiro.', 150, 'Fantasia', '18:00:00');

INSERT INTO PECAS_TEATRO (NOME_PECA, DESCRICAO, DURACAO, TEMA, HORARIO)
VALUES ('A Comédia dos Erros', 'Uma divertida comédia de Shakespeare sobre identidade trocada e confusões.', 145, 'Comédia', '20:30:00');
SELECT * FROM PECAS_TEATRO

-- 2
DELIMITER $$
CREATE PROCEDURE CALCULAR_MEDIA_DURACAO(IN ID INT) 
BEGIN 
	SELECT AVG (DURACAO) FROM PECAS_TEATRO WHERE ID_PECA=ID;
END
DELIMITER $$

-- 3
DELIMITER $$
CREATE PROCEDURE VERIFICAR_DISPONIBILIDADE(IN HORA VARCHAR(10))
BEGIN
	SELECT TIME(HORARIO) FROM PECAS_TEATRO AS HORARIO_DISNPONIVEL WHERE HORARIO=HORA;
END
DELIMITER $$
CALL VERIFICAR_DISPONIBILIDADE('20:00:00')

-- 4
DELIMITER $$
CREATE PROCEDURE AGENDAR_PECA 
(
    IN PAR_NOME_PECA VARCHAR(100), 
    IN PAR_DESCRICAO VARCHAR(800), 
    IN PAR_DURACAO INT, 
    IN PAR_TEMA VARCHAR(50), 
    IN PAR_DATA_HORA VARCHAR(10)
)
BEGIN
    INSERT INTO PECAS_TEATRO (NOME_PECA, DESCRICAO, DURACAO, TEMA, HORARIO)
    VALUES (PAR_NOME_PECA, PAR_DESCRICAO, PAR_DURACAO, PAR_TEMA, PAR_DATA_HORA);
    CALL VERIFICAR_DISPONIBILIDADE(PAR_DATA_HORA)
    
   SELECT PECAS.*, (SELECT AVG(DURACAO) FROM PECAS_TEATRO) AS MEDIA_DURACAO FROM 
    PECAS_TEATRO PECAS  WHERE PECAS.NOME_PECA= PAR_NOME_PECA
END
DELIMITER $$

-- 5
-- SET SQL_SAFE_UPDATES = 0;
-- DELETE FROM PECAS_TEATRO WHERE NOME_PECA = 'Hamlet'
CALL AGENDAR_PECA('Hamlet', 'Uma tragédia de Shakespeare sobre o príncipe da Dinamarca.', 180, 'Tragédia', '19:00:00');















-- DROP DATABASE TEATRO;